import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {  
  return (
    <>
      <Head>
        <title>Blog Makes Money</title>
        <meta name="description" content="Generated by create next app with code with harry" />
        <meta name="viewport" content="next js blog website" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}><ul>
        <li><a href="/">Home</a> </li>
        <li><a href="/about">About</a></li>
        <li> <a href="/blogs"> Blogs</a></li>
        <li> <a href="/contact">contact</a> </li></ul></nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          BlogsCode
        </h1>
        <div className={styles.para}>
          <h2>A blogs page for all the enthuastic coder ... try to upload daily. </h2>
        </div >
        <div className={styles.blogarea}>
          Popular Blogs <br /><br />
          <div className="blogs">
            <div className={styles.blogitem}>
              <h3> How to learn js 2023!!</h3>
              <p>js description  : Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit dolorum exercitationem quae nostrum, vitae a quos qui modi quis dignissimos quisquam minima incidunt fugit, quam sapiente natus debitis assumenda expedita.</p><br />
            </div>
            <div className={styles.blogitem}>
              <h3> How to learn js 2023!!</h3>
              <p>js description  : Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit dolorum exercitationem quae nostrum, vitae a quos qui modi quis dignissimos quisquam minima incidunt fugit, quam sapiente natus debitis assumenda expedita.</p><br />
            </div><div className={styles.blogitem}>
              <h3> How to learn js 2023!!</h3>
              <p>js description  : Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit dolorum exercitationem quae nostrum, vitae a quos qui modi quis dignissimos quisquam minima incidunt fugit, quam sapiente natus debitis assumenda expedita.</p><br />
            </div><div className={styles.blogitem}>
              <h3> How to learn js 2023!!</h3>
              <p>js description  : Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit dolorum exercitationem quae nostrum, vitae a quos qui modi quis dignissimos quisquam minima incidunt fugit, quam sapiente natus debitis assumenda expedita.</p><br />
            </div>
          </div>
        </div>



      </main>
    </>
  )
}
